type Company {
  id: ID,
  name: String @fake(type:companyName)
  industry: String @examples(values: ["IT", "Manufacturing", "Medicine", "Media"])
  employees: [Employee!]
  banner: String @fake(type: imageUrl, options: {imageCategory: business, imageWidth:200, imageHeight: 750})
  profile: String @fake(type: lorem),
}

type Employee {
  id: ID
  firstName: String @fake(type: firstName, locale:en_CA)
  lastName: String @fake(type: lastName, locale:en_CA)
  address: String @fake(type:streetAddress, options: { useFullAddress: true })
  subordinates: [Employee!]
  company: Company
  avatar: String @fake(type: imageUrl, options: {imageCategory: cats, imageWidth:250, imageHeight: 250})
  role: String @fake(type: jobTitle),
  profile: String @fake(type: lorem),
}

type Navigation {
  home:String @examples(values: ["Home"])
  work: String @examples(values: ["Work"])
  over: String @examples(values: ["Over"])
  services: String @examples(values: ["Services"])
  partners: String @examples(values: ["Partners"])
  stories: String @examples(values: ["Stories"])
  careers: String @examples(values: ["Careers"])
  contact: String @examples(values: ["Contact"])
}

type Tags {
  home:String @examples(values: ["This is us:"])
  work: String @examples(values: ["Were so proud of:"])
  over: String @examples(values: ["A little about us"])
  services: String @examples(values: ["Also.. stuff.."])
  partners: String @examples(values: ["With friends like these.."])
  stories: String @examples(values: ["Gather round kids, its storytime"])
  careers: String @examples(values: ["Just hire me."])
  contact: String @examples(values: ["Drop us a line"])
}

type Locales {
  en_en:String @examples(values: ["Global"])
  nl_nl: String @examples(values: ["Nederland"])
  de_de: String @examples(values: ["Deutchland"])
  en_gb: String @examples(values: ["United Kingdom"])
  en_ie: String @examples(values: ["Ireland"])
  de_ch: String @examples(values: ["Schweiz"])
  da_dk: String @examples(values: ["Denmark"])
  en_us: String @examples(values: ["United States"])
}

type Article {
  id: ID,
  title: String @fake(type:productMaterial)
  banner: String @fake(type: imageUrl, options: { imageWidth:300, imageHeight: 750})
  profile: String @fake(type: lorem),
}

type Query {
  navItems(country: String): Navigation
  tagLines(country: String): Tags
  getArticle(country: String, id: String): Article
  locales: Locales
  employees: [Employee!]
  company(id: ID): Company
  allCompanies: [Company!]
}
